#-- General configuration 

light_speed: 299792.458  # km/s

n_phases: 25
n_reals: 27
comp_field: "Y3_COMP"  # completeness field: Y1_COMP, Y3_COMP, or Y5
zsnap: 0.10 

version_bgs_base: "v3.0"
version_bgs_spec: "v3.0"
version_bgs_clus: "v3.0"
version_fp_full: "v3.0"
version_fp_clus: "v3.0"
version_tf_full: "v3.0"
version_tf_clus: "v3.0"

mock_dir: "/global/cfs/cdirs/desi/science/td/pv/mocks/DR2"

mock_bgs_base_dir: "{mock_dir}/BGS_base/{version_bgs_base}"
mock_bgs_base_data: "{mock_bgs_base_dir}/data/BGS_PV_AbacusSummit_base_c000_ph{{phase:03d}}_r{{real:03d}}_zsnap0.10_zmax0.11.dat.hdf5"
mock_bgs_base_rand: "{mock_bgs_base_dir}/rand/BGS_PV_AbacusSummit_base_c000_ph{{phase:03d}}_r{{real:03d}}_zsnap0.10_zmax0.11.ran.hdf5"

mock_bgs_spec_dir: "{mock_dir}/BGS_{spec_name}/{version_bgs_spec}"
mock_bgs_spec_data: "{mock_bgs_spec_dir}/BGS_PV_AbacusSummit_spec_c000_ph{{phase:03d}}_r{{real:03d}}.dat.hdf5"
mock_bgs_spec_plot_dir: "{mock_bgs_spec_dir}/plots"

mock_bgs_clus_dir: "{mock_dir}/BGS_clustering/{version_bgs_clus}"
mock_bgs_clus_data: "{mock_bgs_clus_dir}/data/BGS_PV_AbacusSummit_clustering_c000_ph{{phase:03d}}_r{{real:03d}}.fits"
mock_bgs_clus_rand: "{mock_bgs_clus_dir}/rand/BGS_PV_AbacusSummit_clustering_random{n_reals}x_ph{{phase:03d}}.fits"

mock_fp_full_dir: "{mock_dir}/FP_mocks/full_mocks/{version_fp_full}"
mock_fp_full_data: "{mock_fp_full_dir}/FP_AbacusSummit_c000_ph{{phase:03d}}_r{{real:03d}}.fits"

mock_fp_clus_dir: "{mock_dir}/FP_mocks/clustering_mocks/{version_fp_clus}"
mock_fp_clus_data: "{mock_fp_clus_dir}/data/FP_AbacusSummit_clustering_c000_ph{{phase:03d}}_r{{real:03d}}.fits"
mock_fp_clus_rand: "{mock_fp_clus_dir}/rand/FP_AbacusSummit_clustering_random{n_reals}x_ph{{phase:03d}}.fits"

mock_tf_full_dir: "{mock_dir}/TF_mocks/full_mocks/{version_tf_full}"
mock_tf_full_data: "{mock_tf_full_dir}/TF_AbacusSummit_c000_ph{{phase:03d}}_r{{real:03d}}.fits"

mock_tf_clus_dir: "{mock_dir}/TF_mocks/clustering_mocks/{version_tf_clus}"
mock_tf_clus_data: "{mock_tf_clus_dir}/data/TF_AbacusSummit_clustering_c000_ph{{phase:03d}}_r{{real:03d}}.fits"
mock_tf_clus_rand: "{mock_tf_clus_dir}/rand/TF_AbacusSummit_clustering_random{n_reals}x_ph{{phase:03d}}.fits"

#-- Data paths
data_dir: "/global/cfs/cdirs/desi/science/td/pv"

data_bgs_clus_data: "{data_dir}/bgsclustering/Y3/BGS_BRIGHT_clustering_forPV_data_Mr_lt_-19.0.fits"
data_bgs_clus_rand: "{data_dir}/bgsclustering/Y3/BGS_BRIGHT_clustering_forPV_random_Mr_lt_-19.0.fits"

data_fp_full_version: "v1"
data_n_rand: 20
data_fp_full: "{data_dir}/fpgalaxies/Y3/{data_fp_full_version}/FP_pv_cat_{data_fp_full_version}.csv"
data_fp_clus_data: "{data_dir}/fpgalaxies/Y3/{data_fp_full_version}/FP_clustering_data_{data_fp_full_version}.fits"
data_fp_clus_rand: "{data_dir}/fpgalaxies/Y3/{data_fp_full_version}/FP_clustering_random20_{data_fp_full_version}.fits"

data_tf_full_version: "v3"  # By Sara Moore
data_tf_full: "{data_dir}/tfgalaxies/Y3/DESI-DR2_TF_pv_cat_{data_tf_full_version}.fits"
data_tf_pickle: "{data_dir}/tfgalaxies/Y3/..."
data_tf_clus_data: "{data_dir}/tfgalaxies/Y3/TF_clustering_data_{data_tf_full_version}.fits"
data_tf_clus_rand: "{data_dir}/tfgalaxies/Y3/TF_clustering_random20_{data_tf_full_version}.fits"

kcorr_file: "/global/cfs/cdirs/desi/science/td/pv/mocks/BGS_base/k_corr_rband_z01.dat"
kcorr_r_path: "/global/cfs/cdirs/desi/science/td/pv/mocks/FP_mocks/k_corr_rband_z01.dat"
kcorr_g_path: "/global/cfs/cdirs/desi/science/td/pv/mocks/FP_mocks/k_corr_gband_z01.dat"

sga_file: "/global/cfs/cdirs/cosmo/data/sga/2020/SGA-2020.fits"
dust_map: "/global/cfs/cdirs/desi/public/papers/mws/desi_dust/y2/v1/maps/desi_dust_gr_512.fits"

#-- Spectroscopic information from real data to be matched to mocks
spec_name: "loa"
spec_csv: "/global/cfs/cdirs/desi/science/td/pv/redshift_data/Y3/loa_fullsweep_catalogue_z010.csv"
spec_keys:
  - targetid
  - survey
  - program
  - healpix
  - morphtype
  - z
  - zwarn
  - mag_r
  - flux_g
  - flux_r
  - flux_z
  - mag_g
  - mag_z
  - sersic
  - sersic_ivar
  - circ_radius
  - circ_radius_err
  - pos_angle
  - BA_ratio
#  - sfr
#  - logmstar

match_keys:
  - targetid
  - survey
  - program
  - healpix

#- BGS mocks with assigned spectroscopic quantities
bgs_spec:
  overwrite: false
  deltachi2_min: 30.0
  zmax: 0.11
  r_mag_lim: 19.7
  col_min: -0.5
  col_max: 1.5
  do_diagnostic_plots: true

#- BGS clustering mocks for density field
bgs_clus:
  overwrite: true
  phase: -1
  subsample_nz: true # -- subsample to match data n(z)
  comp_min: 0.5
  zmin: 0.01
  zmax: 0.10
  nzbin: 36
  appmaglim: 20.0 
  absmaglim: -19.0 #--  -17.7
  ngrid: 128
  power_dd_fkp: 1600.0

#- Fundamental Plane full mocks
fp_full:
  overwrite: true

  # FP parameters (fit to data)
  a: 1.182
  b: -0.803
  rmean: 0.256
  smean: 2.131
  imean: 2.457
  sigma1: 0.058
  sigma2: 0.456
  sigma3: 0.224

  # Photometric and kinematic cuts
  mag_low: 10.0
  mag_high: 19.0 #- it's 18.0 for real data
  zmin: 0.0033
  zmax: 0.1
  comp_min: 0.5
  smin: 1.6989700043360187  # log10(50.0)
  smax: 2.6232492903979003  # log10(420.0)

  # Physical corrections
  evo_corr: 1.1
  evo_corr_err: 0.4
  sigma_corr_exp: -0.06
  sigma_corr_exp_err: 0.03
  theta_ap: 0.75  # fibre radius in arcsec

  # Grid for log-distance calculation
  dmin: -1.4
  dmax: 1.4
  nd: 1001

#- Tully-Fisher full mocks
tf_full:
  overwrite: false

  # Matching
  center_match_frac: 0.1  # (angular sep) / (D26/2) threshold

  # Velocity limits for CDF re-sampling [log10(km/s)]
  logv_min: 1.0
  logv_max: 3.0

  # Binning
  min_bin_count: 50
  mr_bin_width: 0.05

  # TFR fitting
  calib_sample_size: 4200
  n_realisations: 25

  # Velocity error floor [km/s]
  logv_err_floor: 7.0

#- Fundamental Plane clustering mocks for velocity field
fp_clus:
  overwrite: true
  phase: -1
  zmin: 0.01
  zmax: 0.10
  comp_min: 0.5
  rfact: 20
  ngrid: 128
  nzbin: 36
  power_vv_fkp: 5e9 


#- Tully-fisher clustering mocks for velocity field
tf_clus:
  overwrite: true
  zmin: 0.01
  zmax: 0.10
  comp_min: 0.5
  rfact: 20
  ngrid: 128
  nzbin: 36
  power_vv_fkp: 5e9 